Add files via upload

diff --git a/izmit-install b/izmit-install
--- a/izmit-install
+++ b/izmit-install
@@ -33,57 +33,68 @@ function logerr {
     printf "${LRED}"
 }
 
-printf "\n${LPURPLE}Izmit: Install v2 by Kamila Palaiologos Szewczyk. Copyright (C) 2018. License: MIT${RESTORE}\n"
-
 if [ "$#" -ne 1 ]; then
+    if [ -f "izmitfile" ]; then
+        . ./izmitfile
+        for i in "${PACKAGES[@]}"; do
+            install "$i"
+        done
+        exit
+    fi
+
     logerr
     printf "Usage: izmitinstall package-name ${RESTORE}\n"
     exit
 fi
 
-log
-printf "Installing $1 ...${RESTORE}\n"
+function install {
 
-start=`date +%s`
+    log
+    printf "Installing $1 ...${RESTORE}\n"
 
-log
-printf "Verifying izmit_modules ...${RESTORE}\n"
+    start=`date +%s`
 
-mkdir izmit_modules
-cd izmit_modules
+    log
+    printf "Verifying izmit_modules ...${RESTORE}\n"
 
-log
-printf "Fetching $1 ...${RESTORE}\n"
+    cd izmit_modules
 
-branchName=""
-packageName=""
+    log
+    printf "Fetching $1 ...${RESTORE}\n"
 
-if [[ $1 == *"@"* ]]; then
-    IFS='@' read -r -a array <<< "$1"
-    wget "https://github.com/IzmitPM/${array[0]}/archive/${array[1]}.zip" > /dev/null 2> /dev/null
-    branchName=$array[1]
-    packageName=$array[0]
-else
-    wget "https://github.com/IzmitPM/$1/archive/master.zip" > /dev/null 2> /dev/null
-    branchName="master"
-    packageName=$1
-fi
+    branchName=""
+    packageName=""
 
-if [ $? -ne 0 ]; then
-    logerr
-    printf "Couldn't fetch $packageName from $branchName branch.${RESTORE}\n"
-    exit
-fi
+    if [[ $1 == *"@"* ]]; then
+        IFS='@' read -r -a array <<< "$1"
+        wget "https://github.com/IzmitPM/${array[0]}/archive/${array[1]}.zip" > /dev/null 2> /dev/null
+        branchName=$array[1]
+        packageName=$array[0]
+    else
+        wget "https://github.com/IzmitPM/$1/archive/master.zip" > /dev/null 2> /dev/null
+        branchName="master"
+        packageName=$1
+    fi
 
-log
-printf "Fetched $packageName from remote.${RESTORE}\n"
-printf "Unpacking ...${RESTORE}\n"
+    if [ $? -ne 0 ]; then
+        logerr
+        printf "Couldn't fetch $packageName from $branchName branch.${RESTORE}\n"
+        exit
+    fi
 
-unzip $branchName.zip
+    log
+    printf "Fetched $packageName from remote.${RESTORE}\n"
+    printf "Unpacking ...${RESTORE}\n"
 
-printf "Cleaning up archives ...${RESTORE}\n"
+    unzip $branchName.zip
 
-rm $branchName.zip
+    printf "Cleaning up archives ...${RESTORE}\n"
+
+    rm $branchName.zip
+
+}
+
+install "$1"
 
 end=`date +%s`
 total=$((end-start))
